[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name         forward
    Listen       0.0.0.0
    Port         24224

[INPUT]
    Name         tail
    Path         /var/log/loguru/*.log
    Tag          loguru.logs
    Parser       json
    Mem_Buf_Limit 5MB
    Skip_Long_Lines On

[FILTER]
    Name         record_modifier
    Match        *
    Record       container_tag %TAG

[OUTPUT]
    Name         kafka
    Match        *
    Brokers      kafka:9092
    Topics       app-logs
